package com.rit.spms.service;

import com.rit.spms.domain.*;
import com.rit.spms.domain.enums.AnnualEvaluationState;
import com.rit.spms.domain.enums.StrategyType;
import com.rit.spms.dto.request.CreateAchievementRequest;
import com.rit.spms.dto.response.AchievementResponse;
import com.rit.spms.exception.BusinessRuleException;
import com.rit.spms.exception.ResourceNotFoundException;
import com.rit.spms.exception.UnauthorizedException;
import com.rit.spms.repository.*;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Service
@RequiredArgsConstructor
@Transactional
public class AchievementService {

    private final AchievementRepository achievementRepository;
    private final MeasurementRepository measurementRepository;
    private final AchievementTypeRepository achievementTypeRepository;
    private final AssessmentPeriodRepository assessmentPeriodRepository;
    private final AppUserRepository appUserRepository;
    private final InitiativeRepository initiativeRepository;
    private final AcademicYearRepository academicYearRepository;
    private final AnnualEvaluationRepository annualEvaluationRepository;
    private final PermissionService permissionService;
    private final AuditService auditService;

    /** Returns the closed/frozen state of the academic year for a given achievement.
     *  Checks the initiative's academic year first; if null (common for seeded data, and always
     *  true for achievements generated by a criterion-assigned achievement tool -- those have no
     *  measurement at all, see {@code TeachingEvaluationSessionService.finalizeAchievement}), falls
     *  back to matching the assessment period by name. */
    private boolean isYearFrozen(Achievement a) {
        return resolveAcademicYear(a) != null && Boolean.TRUE.equals(resolveAcademicYear(a).getClosed());
    }

    /** The academic year an achievement belongs to, for locking purposes -- same
     *  initiative-year-first-then-period-name-fallback resolution as {@link #isYearFrozen}. Public
     *  so PortfolioEntryService can reuse it to decide whether a viewer is the chair assigned to
     *  review this achievement's author for that year (see PortfolioEntryService.canViewGoalLink). */
    public AcademicYear resolveAcademicYear(Achievement a) {
        AcademicYear ay = a.getMeasurement() != null ? a.getMeasurement().getInitiative().getAcademicYear() : null;
        if (ay == null && a.getAssessmentPeriod() != null) {
            ay = academicYearRepository.findByName(a.getAssessmentPeriod().getName()).orElse(null);
        }
        return ay;
    }

    /** The Strategy an achievement belongs to, or null for achievements with no measurement at all
     *  (created by a criterion-assigned achievement tool directly against a portfolio entry, never
     *  attached to any Initiative) -- those have no "strategy owner" concept, so only their own
     *  author can ever edit/delete them. */
    private Strategy resolveStrategy(Achievement a) {
        return a.getMeasurement() != null
                ? a.getMeasurement().getInitiative().getObjective().getGoal().getStrategy()
                : null;
    }

    /**
     * Once the author's Annual Evaluation for this achievement's academic year has been submitted
     * to the department chair for review (or moved further along), the achievement it's tagged
     * against must be frozen in the Strategy Tree -- otherwise the employee could keep changing
     * the evidence behind a rating the chair has already started reviewing.
     */
    private boolean isSubmittedForReview(Achievement a) {
        AcademicYear ay = resolveAcademicYear(a);
        if (ay == null) return false;
        return annualEvaluationRepository.findByEmployeeIdAndAcademicYearId(a.getAuthor().getId(), ay.getId())
                .map(e -> e.getState() != AnnualEvaluationState.DRAFT
                        && e.getState() != AnnualEvaluationState.RETURNED_TO_EMPLOYEE)
                .orElse(false);
    }

    public Achievement recordAchievement(Long measurementId, CreateAchievementRequest req, Long currentUserId) {
        Measurement measurement = measurementRepository.findById(measurementId)
                .orElseThrow(() -> new ResourceNotFoundException("Measurement", measurementId));

        Strategy strategy = measurement.getInitiative().getObjective().getGoal().getStrategy();

        if (strategy.getStrategyType() == StrategyType.UNIVERSITY) {
            throw new BusinessRuleException(
                    "Achievements cannot be recorded directly on the university strategy. " +
                    "They are aggregated automatically from department strategies.");
        }

        // Block recording against a closed academic year
        AcademicYear academicYear = measurement.getInitiative().getAcademicYear();
        if (academicYear != null && academicYear.getClosed()) {
            throw new BusinessRuleException(
                    "Academic year '" + academicYear.getName() + "' is closed. No new achievements can be recorded.");
        }

        permissionService.assertCanAddAchievement(currentUserId, strategy.getId());

        AppUser author = appUserRepository.findById(currentUserId)
                .orElseThrow(() -> new ResourceNotFoundException("AppUser", currentUserId));

        AchievementType type = achievementTypeRepository.findById(req.getAchievementTypeId())
                .orElseThrow(() -> new ResourceNotFoundException("AchievementType", req.getAchievementTypeId()));

        boolean isOtherType = "Other".equalsIgnoreCase(type.getName());
        if (isOtherType && (req.getCustomTypeName() == null || req.getCustomTypeName().isBlank())) {
            throw new BusinessRuleException("Describe the achievement type when selecting \"Other\"");
        }

        if (req.getAssessmentPeriodId() == null) {
            throw new BusinessRuleException("An assessment period must be selected when recording an achievement");
        }
        AssessmentPeriod period = assessmentPeriodRepository.findById(req.getAssessmentPeriodId())
                .orElseThrow(() -> new ResourceNotFoundException("AssessmentPeriod", req.getAssessmentPeriodId()));

        Achievement achievement = Achievement.builder()
                .measurement(measurement)
                .title(req.getTitle())
                .achievementType(type)
                .customTypeName(isOtherType ? req.getCustomTypeName() : null)
                .details(req.getDetails())
                .privateNotes(req.getPrivateNotes())
                .author(author)
                .assessmentPeriod(period)
                .build();
        achievement = achievementRepository.save(achievement);

        auditService.log(author, "RECORD_ACHIEVEMENT", "Achievement", achievement.getId(), strategy,
                "Recorded achievement: " + achievement.getTitle());
        return achievement;
    }

    public Achievement updateAchievement(Long achievementId, CreateAchievementRequest req, Long currentUserId) {
        Achievement achievement = achievementRepository.findById(achievementId)
                .orElseThrow(() -> new ResourceNotFoundException("Achievement", achievementId));

        Strategy strategy = resolveStrategy(achievement);

        if (isYearFrozen(achievement)) {
            throw new BusinessRuleException("This academic year is frozen. Achievements cannot be edited.");
        }
        if (isSubmittedForReview(achievement)) {
            throw new BusinessRuleException(
                    "This achievement has been submitted for annual evaluation review and can no longer be edited.");
        }

        boolean isAuthor = achievement.getAuthor().getId().equals(currentUserId);
        boolean isOwner = strategy != null && permissionService.isOwner(currentUserId, strategy.getId());

        if (!isAuthor && !isOwner) {
            throw new UnauthorizedException("Only the achievement author or strategy Owner can edit this achievement");
        }

        AppUser user = appUserRepository.findById(currentUserId)
                .orElseThrow(() -> new ResourceNotFoundException("AppUser", currentUserId));

        String oldTitle = achievement.getTitle();
        achievement.setTitle(req.getTitle());
        // Details are AI-generated (or otherwise produced) by the achievement-recording tool itself
        // for module-created achievements -- never editable, regardless of what the disabled UI
        // field submits.
        if (req.getDetails() != null && achievement.getCreatedByModuleCode() == null) {
            achievement.setDetails(req.getDetails());
        }
        if (req.getPrivateNotes() != null) achievement.setPrivateNotes(req.getPrivateNotes());

        if (req.getAchievementTypeId() != null) {
            AchievementType type = achievementTypeRepository.findById(req.getAchievementTypeId())
                    .orElseThrow(() -> new ResourceNotFoundException("AchievementType", req.getAchievementTypeId()));
            boolean isOtherType = "Other".equalsIgnoreCase(type.getName());
            if (isOtherType && (req.getCustomTypeName() == null || req.getCustomTypeName().isBlank())) {
                throw new BusinessRuleException("Describe the achievement type when selecting \"Other\"");
            }
            achievement.setAchievementType(type);
            achievement.setCustomTypeName(isOtherType ? req.getCustomTypeName() : null);
        }

        // Assessment period is fixed at creation and never editable afterward -- every achievement
        // must belong to a period, so nothing here can move or clear it. Any assessmentPeriodId on
        // this request is ignored.

        achievement = achievementRepository.save(achievement);
        auditService.log(user, "UPDATE_ACHIEVEMENT", "Achievement", achievementId, strategy,
                oldTitle, achievement.getTitle(), "Updated achievement");
        return achievement;
    }

    /**
     * Admin repair tool: moves an achievement off a "base" (year-less) measurement onto the
     * year-specific copy matching its own assessment period name -- for achievements recorded
     * before a strategy's late deployment triggered the backfill (see
     * AcademicYearService.backfillInitiativeCopiesForNewlyDeployedStrategy), which otherwise stay
     * permanently invisible under every specific academic-year filter in the Strategy tree, no
     * matter which period they're tagged with.
     */
    public Achievement relocateToMatchingYear(Long achievementId) {
        Achievement achievement = achievementRepository.findById(achievementId)
                .orElseThrow(() -> new ResourceNotFoundException("Achievement", achievementId));
        Measurement current = achievement.getMeasurement();
        if (current.getAcademicYear() != null) {
            throw new BusinessRuleException("This achievement is already on a year-specific measurement");
        }
        if (achievement.getAssessmentPeriod() == null) {
            throw new BusinessRuleException("This achievement has no assessment period to match against");
        }
        AcademicYear year = academicYearRepository.findByName(achievement.getAssessmentPeriod().getName())
                .orElseThrow(() -> new BusinessRuleException(
                        "No academic year named '" + achievement.getAssessmentPeriod().getName() + "' exists"));
        Measurement target = measurementRepository.findBySourceMeasurementIdAndAcademicYearId(current.getId(), year.getId())
                .orElseThrow(() -> new BusinessRuleException(
                        "No year-specific measurement copy exists for '" + year.getName() + "' yet -- the strategy may need to be redeployed to trigger the backfill"));
        achievement.setMeasurement(target);
        return achievementRepository.save(achievement);
    }

    public void deleteAchievement(Long achievementId, Long currentUserId) {
        Achievement achievement = achievementRepository.findById(achievementId)
                .orElseThrow(() -> new ResourceNotFoundException("Achievement", achievementId));

        Strategy strategy = resolveStrategy(achievement);

        if (isYearFrozen(achievement)) {
            throw new BusinessRuleException("This academic year is frozen. Achievements cannot be deleted.");
        }
        if (isSubmittedForReview(achievement)) {
            throw new BusinessRuleException(
                    "This achievement has been submitted for annual evaluation review and can no longer be deleted.");
        }

        boolean isAuthor = achievement.getAuthor().getId().equals(currentUserId);
        boolean isOwner = strategy != null && permissionService.isOwner(currentUserId, strategy.getId());

        if (!isAuthor && !isOwner) {
            throw new UnauthorizedException("Only the achievement author or strategy Owner can delete this achievement");
        }

        AppUser user = appUserRepository.findById(currentUserId)
                .orElseThrow(() -> new ResourceNotFoundException("AppUser", currentUserId));

        auditService.log(user, "DELETE_ACHIEVEMENT", "Achievement", achievementId, strategy,
                "Deleted achievement: " + achievement.getTitle());
        achievementRepository.delete(achievement);
    }

    @Transactional(readOnly = true)
    public List<AchievementResponse> getAchievements(Long measurementId, Long currentUserId) {
        Measurement measurement = measurementRepository.findById(measurementId)
                .orElseThrow(() -> new ResourceNotFoundException("Measurement", measurementId));
        permissionService.assertCanRead(currentUserId,
                measurement.getInitiative().getObjective().getGoal().getStrategy().getId());

        return achievementRepository.findByMeasurementIdOrderByRecordedAtDesc(measurementId)
                .stream().map(a -> toResponse(a, currentUserId)).toList();
    }

    /**
     * Union of a base initiative's own achievements plus every academic-year copy's -- used by the
     * "Base Plan" (no year selected) view so achievements recorded against a specific year's copy
     * still surface instead of looking like they've disappeared.
     */
    @Transactional(readOnly = true)
    public List<AchievementResponse> getAchievementsAcrossYears(Long initiativeId, String periodName, Long currentUserId) {
        Initiative initiative = initiativeRepository.findById(initiativeId)
                .orElseThrow(() -> new ResourceNotFoundException("Initiative", initiativeId));
        permissionService.assertCanRead(currentUserId,
                initiative.getObjective().getGoal().getStrategy().getId());

        List<Achievement> achievements = (periodName != null && !periodName.isBlank())
                ? achievementRepository.findByBaseInitiativeIdAcrossYearsAndPeriodName(initiativeId, periodName)
                : achievementRepository.findByBaseInitiativeIdAcrossYears(initiativeId);
        return achievements.stream().map(a -> toResponse(a, currentUserId)).toList();
    }

    @Transactional(readOnly = true)
    public List<AchievementResponse> getAggregatedAchievements(Long universityInitiativeId, Long currentUserId) {
        Initiative initiative = initiativeRepository.findById(universityInitiativeId)
                .orElseThrow(() -> new ResourceNotFoundException("Initiative", universityInitiativeId));
        permissionService.assertCanRead(currentUserId,
                initiative.getObjective().getGoal().getStrategy().getId());

        return achievementRepository.findAggregatedByUniversityInitiativeId(universityInitiativeId)
                .stream().map(a -> toResponse(a, currentUserId)).toList();
    }

    public AchievementResponse toResponse(Achievement a, Long viewingUserId) {
        boolean isAuthor = viewingUserId != null && viewingUserId.equals(a.getAuthor().getId());

        boolean yearFrozen = isYearFrozen(a);

        Strategy strategy = resolveStrategy(a);
        boolean isOwner = viewingUserId != null && strategy != null && permissionService.isOwner(viewingUserId, strategy.getId());

        boolean canModify = !yearFrozen && !isSubmittedForReview(a) && (isOwner || isAuthor);

        return AchievementResponse.builder()
                .id(a.getId())
                .measurementId(a.getMeasurement() != null ? a.getMeasurement().getId() : null)
                .title(a.getTitle())
                .achievementTypeId(a.getAchievementType().getId())
                .achievementTypeName(a.getEffectiveTypeName())
                .customTypeName(a.getCustomTypeName())
                .details(a.getDetails())
                .privateNotes(isAuthor ? a.getPrivateNotes() : null)
                .authorId(a.getAuthor().getId())
                .authorName(a.getAuthor().getFname() + " " + a.getAuthor().getLname())
                .assessmentPeriodId(a.getAssessmentPeriod() != null ? a.getAssessmentPeriod().getId() : null)
                .assessmentPeriodName(a.getAssessmentPeriod() != null ? a.getAssessmentPeriod().getName() : null)
                .recordedAt(a.getRecordedAt())
                .updatedAt(a.getUpdatedAt())
                .canEdit(canModify)
                .canDelete(canModify)
                .build();
    }
}
